import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const navLinks = [
  { href: '/products', title: 'Products' },
  { href: '/stories', title: 'Stories' },
  { href: '/about-us', title: 'About us' },
  { href: '/contacts', title: 'Contacts' },
];

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="w-full p-4">
      <div className="max-w-screen-xl flex justify-around">
        <Link href="/" className="flex items-center">
          <Image src="/logo-white.png" width={120} height="120" alt="Pirtsslotas Logo" />
        </Link>
        <div className="flex items-center space-x-12">
          {navLinks.map((link, index) => (
              <Link key={index} href={link.href}>{link.title}</Link>
          ))}
        </div>
      </div>
      </nav>
        {children}
        </body>
    </html>
  )
}
