import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Image from 'next/image'
import {FC,  ReactNode} from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const navLinks = [
  { href: '/products', title: 'Products' },
  { href: '/stories', title: 'Stories' },
  { href: '/about-us', title: 'About us' },
  { href: '/contacts', title: 'Contacts' },
];

import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';
 
export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'de'}];
}
 
export default async function RootLayout({children, params: {locale}}) {

  console.log(locale)

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
 
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
        <nav className="w-full p-4">
      <div className="max-w-screen-xl flex justify-around">
        <Link href="/" className="flex items-center">
          <Image src="/logo-white.png" width={120} height="120" alt="Pirtsslotas Logo" />
        </Link>
        <div className="flex items-center space-x-12">
          {navLinks.map((link, index) => (
              <Link key={index} href={link.href}>{link.title}</Link>
          ))}
        </div>
      </div>
      </nav>
        {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}